# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='逻辑删除')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
            ],
            options={
                'db_table': 'tb_uploadfile',
            },
        ),
    ]
