# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='../utils', verbose_name='文件存储路径'),
        ),
    ]
