# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='逻辑删除')),
                ('action', models.CharField(max_length=128, verbose_name='操作行为')),
                ('data', models.CharField(max_length=512, verbose_name='操作数据')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.CharField(max_length=64, verbose_name='操作人')),
                ('project_id', models.IntegerField(verbose_name='项目id')),
            ],
            options={
                'verbose_name': '操作日志测试',
                'verbose_name_plural': '操作日志测试',
                'db_table': 'tb_operation_log',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='逻辑删除')),
                ('project_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tb_project',
            },
        ),
    ]
